src/objects/Lunch__c.object
<CustomObject>
    <fields>
        <fullName>Appetizer__c</fullName>
        <description>Appetizer</description>
        <label>Appetizer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Lunch Date</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Desert__c</fullName>
        <label>Desert</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Special_Menu__c</fullName>
        <label>Special Menu</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cooking the lunch menu</fullName>
                <color>#FF6600</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch menu ready</fullName>
                <color>#009900</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Special</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Lunch ID.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lunch_Meetup__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Host_Profile_Picture__c</fullName>
        <label>Host Profile Picture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Casual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch &amp; Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-boarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lunch</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch Meetup</label>
    <nameField>
        <displayFormat>LM-{0000000}</displayFormat>
        <label>Lunch Meetup ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunch Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LunchController.cls
public class LunchController {
    
    @AuraEnabled
    public static Lunch__c todaysLunch() {
        Lunch__c lunch = null;
        lunch = buildTodaysLunchMenu();
        return lunch;
    }
    
    @AuraEnabled
    public static List<Lunch_Meetup__c> todaysLunchMeetups() {
        List<Lunch_Meetup__c> lms = null;
        lms = buildTodaysLunchMeetups();
        return lms;
    }
    
    @AuraEnabled
    public static List<String> todaysLunchMeetupsHosts() {
        List<String> lmh = null;
        lmh = buildTodaysLunchMeetupsHosts();
        return lmh;
    }
    
    private static List<Lunch_Meetup__c> getLunchMeetups() {
        try {
            List<Lunch_Meetup__c> lms = [select id, Name__c,
                                   Address__c, Date__c,
                                   Type__c, CreatedById
                                   from Lunch_Meetup__c WHERE Date__c = TODAY LIMIT 10 ];
            return lms;
        }
        catch (Exception e) {
            System.debug('Lunch - Cannot retrieve lunch meetups for today, m=' + e.getMessage());
            return null;
        }
    }
    
    private static List<String> buildTodaysLunchMeetupsHosts() {
        List<String> lmHosts = new List<String>();
        List<String> lmHostIDs = new List<String>();
        
        List<Lunch_Meetup__c> lms = buildTodaysLunchMeetups();
        for (Lunch_Meetup__c lm : lms) {
            lmHostIDs.add(lm.CreatedById);
        }
        
        List<User> users = [select id, Name, SmallPhotoUrl from User Where id IN :lmHostIDs];
        for (User u : users)
            lmHosts.add(u.SmallPhotoUrl);
        return lmHosts;
    }
    
    private static Lunch__c buildTodaysLunchMenu() {
        try {
            Lunch__c todaysLunch = [select id, name,
                                    Appetizer__c, Course__c, Date__c,
                                    Desert__c, Special_Menu__c, Status__c, Type__c, RecordTypeId
                                    from Lunch__c WHERE Date__c = TODAY AND Status__c = 'Lunch menu ready' LIMIT 1 ];
            
            if (todaysLunch == null)
                return null;
            
            return todaysLunch;
        } catch (Exception e) {
            System.debug('Lunch - Cannot retrieve todays lunch, m=' + e.getMessage());
            return null;
        }
    }
    
    private static List<Lunch_Meetup__c> buildTodaysLunchMeetups() {
        try {
            List<Lunch_Meetup__c> lms = [select id, Name__c,
                                         Address__c, Date__c,
                                         Type__c, CreatedBy.SmallPhotoUrl, Host_Profile_Picture__c 
                                         from Lunch_Meetup__c WHERE Date__c = TODAY LIMIT 10 ];
            
            if (lms == null)
                return null;
                        
            return lms;
        } catch (Exception e) {
            System.debug('Lunch - Cannot retrieve todays lunch meetups, m=' + e.getMessage());
            return null;
        }
    }
}