QSF-Lunch Management/src/objects/Lunch__c.object
<CustomObject>
    <fields>
        <fullName>Appetizer__c</fullName>
        <description>Appetizer</description>
        <label>Appetizer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Lunch Date</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Desert__c</fullName>
        <label>Desert</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lunch_Meetups__c</fullName>
        <label>#Lunch Meetups</label>
        <summaryForeignKey>Lunch_Meetup__c.Lunch__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Special_Menu__c</fullName>
        <label>Special Menu</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cooking the lunch menu</fullName>
                <color>#FF6600</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch menu ready</fullName>
                <color>#009900</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Special</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lunch</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Lunch ID.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lunches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QSF-Lunch Management/src/classes/LunchController.cls
public class LunchController {
    
    @AuraEnabled
    public static Lunch__c todaysLunch() {
        Lunch__c lunch = null;
        lunch = buildTodaysLunchMenu();
        return lunch;
    }
    
    private static Lunch__c buildTodaysLunchMenu() {
        try {
            Lunch__c todaysLunch = [select id, name, Lunch_Meetups__c,
                                    Appetizer__c, Course__c, Date__c,
                                    Desert__c, Special_Menu__c, Status__c, Type__c, RecordTypeId
                                    from Lunch__c WHERE Date__c = TODAY AND Status__c = 'Lunch menu ready' LIMIT 1 ];
            
            if (todaysLunch == null)
                return null;
            
            return todaysLunch;
        } catch (Exception e) {
            System.debug('Lunch - Cannot retrieve todays lunch, m=' + e.getMessage());
            return null;
        }
    }
}